#!/usr/bin/env bash
# configure HAproxy
sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install haproxy
sudo cp -a /etc/haproxy/haproxy.cfg{,.orig}
echo "
frontend load_balancer
        bind *:80
	mode http
        option forwardfor
        default_backend webservers
backend webservers
        balance roundrobin
        server 114754-web-01 54.197.92.25:80 check
        server 114754-web-02 52.201.178.115:80 check" >> /etc/haproxy/haproxy.cfg
sudo service haproxy restart
